version: '3.4'

services:
  grocerybooking:
    image: grocerybooking
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 5432:5432
    command: ["node", "--inspect=0.0.0.0:5432", "app.service.ts"]
